"""init advertisement schema

Revision ID: c5c84dafef39
Revises: 
Create Date: 2026-07-07 10:54:18.012627
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c5c84dafef39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='advertisement'
    )
    op.create_table('menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['advertisement.menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_key'),
    schema='advertisement'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='advertisement'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('entra_object_id', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='user_status', schema='advertisement'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='advertisement'
    )
    op.create_index(op.f('ix_advertisement_users_email'), 'users', ['email'], unique=True, schema='advertisement')
    op.create_index(op.f('ix_advertisement_users_entra_object_id'), 'users', ['entra_object_id'], unique=True, schema='advertisement')
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='advertisement'
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=1024), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['advertisement.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='advertisement'
    )
    op.create_index(op.f('ix_advertisement_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='advertisement')
    op.create_index(op.f('ix_advertisement_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False, schema='advertisement')
    op.create_table('menu_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['advertisement.menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['advertisement.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='advertisement'
    )
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['advertisement.videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='advertisement'
    )
    op.create_index(op.f('ix_advertisement_prompts_video_id'), 'prompts', ['video_id'], unique=False, schema='advertisement')
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['advertisement.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['advertisement.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='advertisement'
    )
    op.create_table('generated_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['advertisement.prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='advertisement'
    )
    op.create_index(op.f('ix_advertisement_generated_videos_prompt_id'), 'generated_videos', ['prompt_id'], unique=False, schema='advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisement_generated_videos_prompt_id'), table_name='generated_videos', schema='advertisement')
    op.drop_table('generated_videos', schema='advertisement')
    op.drop_table('user_roles', schema='advertisement')
    op.drop_index(op.f('ix_advertisement_prompts_video_id'), table_name='prompts', schema='advertisement')
    op.drop_table('prompts', schema='advertisement')
    op.drop_table('menu_permissions', schema='advertisement')
    op.drop_index(op.f('ix_advertisement_audit_logs_created_at'), table_name='audit_logs', schema='advertisement')
    op.drop_index(op.f('ix_advertisement_audit_logs_action'), table_name='audit_logs', schema='advertisement')
    op.drop_table('audit_logs', schema='advertisement')
    op.drop_table('videos', schema='advertisement')
    op.drop_index(op.f('ix_advertisement_users_entra_object_id'), table_name='users', schema='advertisement')
    op.drop_index(op.f('ix_advertisement_users_email'), table_name='users', schema='advertisement')
    op.drop_table('users', schema='advertisement')
    op.drop_table('roles', schema='advertisement')
    op.drop_table('menus', schema='advertisement')
    op.drop_table('examples', schema='advertisement')
    # ### end Alembic commands ###
