apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{APP_NAME}}-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{APP_NAME}}
  source:
    repoURL: https://github.com/fnf-process/{{REPO_NAME}}.git
    targetRevision: develop
    path: charts/{{APP_NAME}}
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{APP_NAME}}-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
