#!/bin/bash
# Squad Report Generator — Squad 완료 시 실행 이력 요약 보고서 생성
# 사용법: squad-report-generator.sh <team-name>
#
# 출력: .claude/squad-logs/{team-name}/report.md

set -eo pipefail
trap 'exit 0' ERR

REPO_ROOT="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
LOGS_DIR="$REPO_ROOT/.claude/squad-logs"
TEAM_NAME="${1:-}"

if [ -z "$TEAM_NAME" ]; then
    echo "❌ Usage: squad-report-generator.sh <team-name>" >&2
    exit 0
fi

TEAM_LOG_DIR="$LOGS_DIR/$TEAM_NAME"
if [ ! -d "$TEAM_LOG_DIR" ]; then
    echo "❌ No logs found for team: $TEAM_NAME" >&2
    exit 0
fi

if ! command -v jq &>/dev/null; then
    echo "❌ jq required" >&2
    exit 0
fi

SUMMARY_FILE="$TEAM_LOG_DIR/summary.json"
REPORT_FILE="$TEAM_LOG_DIR/report.md"

# 이벤트 파일 수집
EVENT_COUNT=$(ls "$TEAM_LOG_DIR"/evt-*.json 2>/dev/null | wc -l | tr -d ' ')

if [ "$EVENT_COUNT" -eq 0 ]; then
    echo "⚠️ No events found for team: $TEAM_NAME" >&2
    exit 0
fi

# 요약 데이터 읽기
if [ -f "$SUMMARY_FILE" ]; then
    TOTAL=$(jq -r '.total_events // 0' "$SUMMARY_FILE")
    STARTS=$(jq -r '.agent_starts // 0' "$SUMMARY_FILE")
    STOPS=$(jq -r '.agent_stops // 0' "$SUMMARY_FILE")
    TASKS_CREATED=$(jq -r '.tasks_created // 0' "$SUMMARY_FILE")
    TASKS_COMPLETED=$(jq -r '.tasks_completed // 0' "$SUMMARY_FILE")
    FIRST_EVENT=$(jq -r '.first_event // "N/A"' "$SUMMARY_FILE")
    LAST_EVENT=$(jq -r '.last_event // "N/A"' "$SUMMARY_FILE")
else
    TOTAL=$EVENT_COUNT
    STARTS=0; STOPS=0; TASKS_CREATED=0; TASKS_COMPLETED=0
    FIRST_EVENT="N/A"; LAST_EVENT="N/A"
fi

# 에이전트별 활동 집계
AGENT_TABLE=""
if [ -f "$SUMMARY_FILE" ]; then
    AGENT_TABLE=$(jq -r '.agents // {} | to_entries | sort_by(-.value) | .[] | "| \(.key) | \(.value) |"' "$SUMMARY_FILE" 2>/dev/null)
fi

# 타임라인 생성 (최근 20개 이벤트)
TIMELINE=""
for evt_file in $(ls -t "$TEAM_LOG_DIR"/evt-*.json 2>/dev/null | head -20); do
    TS=$(jq -r '.timestamp // ""' "$evt_file" 2>/dev/null)
    TYPE=$(jq -r '.event_type // ""' "$evt_file" 2>/dev/null)
    AGENT=$(jq -r '.data.agent_name // .data.task_id // ""' "$evt_file" 2>/dev/null)
    DETAIL=$(jq -r '.data.subject // .data.agent_type // .data.result_preview // "" | .[:80]' "$evt_file" 2>/dev/null)

    case "$TYPE" in
        agent_start) ICON="🟢" ;;
        agent_stop)  ICON="🔴" ;;
        task_created) ICON="📋" ;;
        task_completed) ICON="✅" ;;
        *) ICON="📝" ;;
    esac

    TIMELINE="$TIMELINE
| ${TS:11:8} | $ICON $TYPE | $AGENT | ${DETAIL:0:60} |"
done

# 보고서 생성
cat > "$REPORT_FILE" <<EOF
# Squad Report: $TEAM_NAME

**Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

## Summary

| Metric | Value |
|--------|-------|
| Total Events | $TOTAL |
| Agent Starts | $STARTS |
| Agent Stops | $STOPS |
| Tasks Created | $TASKS_CREATED |
| Tasks Completed | $TASKS_COMPLETED |
| First Event | $FIRST_EVENT |
| Last Event | $LAST_EVENT |
| Duration | $(python3 -c "
from datetime import datetime
try:
    a=datetime.fromisoformat('${FIRST_EVENT}'.replace('Z','+00:00'))
    b=datetime.fromisoformat('${LAST_EVENT}'.replace('Z','+00:00'))
    d=b-a
    h,r=divmod(int(d.total_seconds()),3600)
    m,s=divmod(r,60)
    print(f'{h}h {m}m {s}s')
except: print('N/A')
" 2>/dev/null) |

## Agent Activity

| Agent | Events |
|-------|--------|
$AGENT_TABLE

## Timeline (Recent 20)

| Time | Event | Agent/Task | Detail |
|------|-------|------------|--------|
$TIMELINE

---
*Generated by squad-event-logger (ClawTeam Event Sourcing pattern)*
EOF

echo "✅ Report: $REPORT_FILE" >&2
exit 0
